-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 15:41:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema store_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `store_project` ;

-- -----------------------------------------------------
-- Schema store_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `store_project` ;

-- -----------------------------------------------------
-- Table `catalogue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue` (
  `id_catalogue` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `parent_id` INT NOT NULL COMMENT 'if parent_id  == -1 then the element is one of roots elements in catalogue tree.\n',
  PRIMARY KEY (`id_catalogue`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goods` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goods` (
  `idgoods` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique index in db witch detrmines atricle in system\n',
  `name` VARCHAR(200) NOT NULL,
  `decription` LONGTEXT NULL,
  `catalogue_id_catalogue` INT NOT NULL,
  PRIMARY KEY (`idgoods`, `catalogue_id_catalogue`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idgoods_UNIQUE` ON `goods` (`idgoods` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goods_has_imgs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goods_has_imgs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goods_has_imgs` (
  `goods_idgoods` INT NOT NULL,
  `goods_catalogue_id_catalogue` INT NOT NULL,
  `imgs_id_img` INT NOT NULL,
  PRIMARY KEY (`goods_idgoods`, `goods_catalogue_id_catalogue`, `imgs_id_img`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `imgs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `imgs` (
  `id_img` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(300) NULL,
  PRIMARY KEY (`id_img`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_img_UNIQUE` ON `imgs` (`id_img` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `catalogue`
-- -----------------------------------------------------
START TRANSACTION;
USE `store_project`;
INSERT INTO `catalogue` (`id_catalogue`, `name`, `description`, `parent_id`) VALUES (1, 'Cars', 'Group 1', -1);
INSERT INTO `catalogue` (`id_catalogue`, `name`, `description`, `parent_id`) VALUES (2, 'BigCars', 'Group 2', -1);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
