export const ADMIN_PANEL_USER_AUTHORIZED = {
    SUCCESS: 'ADMIN_PANEL_USER_AUTHORIZED_SUCCESS',
    FAILED: 'ADMIN_PANEL_USER_AUTHORIZED_FAILED'
};

export const ADMIN_PANEL_GOODS_PANEL = {
    GOODS: {
        GET: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_GET_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_GET_FAILED'
        },
        FILTER: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_FILTER_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_FILTER_FAILED'
        },
        EDIT: {
            OPEN: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_OPEN',
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_FAILED',
            CLOSE: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_CLOSE'
        },
        DELETE: {
            PERMISSION: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_SUCCESS',
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_FAILED',
            CLOSE: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_CLOSE'
        }
    }
};

export const ADMIN_PANEL_USERS_PANEL = {
    USERS: {
        GET: {
            SUCCESS: 'ADMIN_PANEL_USERS_PANEL_USERS_GET_SUCCESS'
        },
        EDIT: {
            OPEN: 'ADMIN_PANEL_USERS_PANEL_USERS_EDIT_OPEN',
            CLOSE: 'ADMIN_PANEL_USERS_PANEL_USERS_EDIT_CLOSE'
        },
        FILTER: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_USERS_FILTER_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_USERS_FILTER_FAILED'
        }
    }
};

export const ADMIN_PANEL_CATALOGUE_CONTROL_PANEL = {
    CATALOGUE: {

    },
    ITEM: {
        EDIT: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_EDIT'
    }
};