export const ADMIN_PANEL_USER_AUTHORIZED = {
    SUCCESS: 'ADMIN_PANEL_USER_AUTHORIZED_SUCCESS',
    FAILED: 'ADMIN_PANEL_USER_AUTHORIZED_FAILED'
};

export const ADMIN_PANEL_GOODS_PANEL = {
    GOODS: {
        GET: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_GET_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_GET_FAILED'
        },
        FILTER: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_FILTER_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_FILTER_FAILED'
        },
        EDIT: {
            OPEN: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_OPEN',
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_FAILED',
            CLOSE: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_CLOSE'
        }
    }
};