export const ADD_GOODS_TO_BASKET = 'ADD_GOODS_TO_BASKET';

export const DEL_GOODS_FROM_BASKET = 'DEL_GOODS_FROM_BASKET';

export const INIT_BASKET = 'INIT_BASKET';

export const SHOW_GOODS = {
    SUCCESS: 'SHOW_GOODS_IN_BASKET_SUCCESS',
    FAILED: 'SHOW_GOODS_IN_BASKET_FAILED'
};

export const SAVE_BASKET = {
    SUCCESS: 'SAVE_BASKET_SUCCESS',
    FAILED: 'SAVE_BASKET_FAILED'
};

export const SHOW_HISTORY_BASKET = {
    SUCCESS: 'SHOW_HISTORY_BASKET_SUCCESS',
    FAILED: 'SHOW_HISTORY_BASKET_FAILED'
};

export const SHOW_MAIN_CONTENT = {
    SHOPPING_BASKET: 'SHOW_MAIN_CONTENT_SHOPPING_BASKET',
    USER_HISTORY: 'SHOW_MAIN_CONTENT_USER_HISTORY',
    CATALOGUE: 'SHOW_MAIN_CONTENT_CATALOGUE',
    USER_PROFILE: 'SHOW_MAIN_CONTENT_USER_PROFILE'
};

export const USER = {
    SHOW_INFO: {
        SUCCESS: 'USER_SHOW_INFO_SUCCESS',
        FAILED: 'USER_SHOW_INFO_FAILED'
    },
    SET_INFO: {
        SUCCESS: 'USER_SET_INFO_SUCCESS',
        FAILED: 'USER_SET_INFO_FAILED'
    },
    LOGIN: {
        ASK: 'USER_LOGIN_ASK'
    }
};

export const ERROR = {
    ADD: 'ERROR_ADD',
    DELETE: 'ERROR_DELETE'
};
