export const ADD_GOODS_TO_BASKET = 'ADD_GOODS_TO_BASKET';
export const DEL_GOODS_FROM_BASKET = 'DEL_GOODS_FROM_BASKET';
export const SHOW_GOODS = {
    SUCCESS: 'SHOW_GOODS_IN_BASKET_SUCCESS',
    FAILED: 'SHOW_GOODS_IN_BASKET_FAILED'
};
