export const ADMIN_PANEL_USER_AUTHORIZED = {
    SUCCESS: 'ADMIN_PANEL_USER_AUTHORIZED_SUCCESS',
    FAILED: 'ADMIN_PANEL_USER_AUTHORIZED_FAILED'
};

export const ADMIN_PANEL_GOODS_PANEL = {
    GOODS: {
        GET: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_GET_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_GET_FAILED'
        },
        FILTER: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_FILTER_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_FILTER_FAILED'
        },
        EDIT: {
            OPEN: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_OPEN',
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_FAILED',
            CLOSE: 'ADMIN_PANEL_GOODS_PANEL_GOODS_EDIT_CLOSE'
        },
        DELETE: {
            PERMISSION: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_SUCCESS',
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_FAILED',
            CLOSE: 'ADMIN_PANEL_GOODS_PANEL_GOODS_DELETE_CLOSE'
        }
    }
};

export const ADMIN_PANEL_USERS_PANEL = {
    USERS: {
        GET: {
            SUCCESS: 'ADMIN_PANEL_USERS_PANEL_USERS_GET_SUCCESS'
        },
        EDIT: {
            OPEN: 'ADMIN_PANEL_USERS_PANEL_USERS_EDIT_OPEN',
            CLOSE: 'ADMIN_PANEL_USERS_PANEL_USERS_EDIT_CLOSE'
        },
        FILTER: {
            SUCCESS: 'ADMIN_PANEL_GOODS_PANEL_USERS_FILTER_SUCCESS',
            FAILED: 'ADMIN_PANEL_GOODS_PANEL_USERS_FILTER_FAILED'
        }
    }
};

export const ADMIN_PANEL_CATALOGUE_CONTROL_PANEL = {
    CATALOGUE: {

    },
    ITEM: {
        EDIT: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_EDIT',
        ADD: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_ADD',
        CLOSE_EDIT: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_CLOSE_EDIT',
        OPEN_EDIT: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_OPEN_EDIT',
        CLOSE_ADD: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_CLOSE_ADD',
        OPEN_ADD: 'ADMIN_PANEL_CATALOGUE_CONTROL_PANEL_ITEM_OPEN_ADD'
    }
};

export const ADMIN_PANEL_IMAGES_CONTROL_PANEL = {
    IMAGE: {
        ADD: {
            SUCCESS: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_ADD_SUCCESS',
            FAILED: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_ADD_FAILED',
            OPEN: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_ADD_OPEN',
            CLOSE: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_ADD_CLOSE'
        },
        EDIT: {
            SUCCESS: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_EDIT_SUCCESS',
            FAILED: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_EDIT_FAILED',
            OPEN: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_EDIT_OPEN',
            CLOSE: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_EDIT_CLOSE'
        },
        DELETE: {
            SUCCESS: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_DELETE_SUCCESS',
            FAILED: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_DELETE_FAILED',
            OPEN: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_DELETE_OPEN',
            CLOSE: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_DELETE_CLOSE'
        },
        FILTERS: {
            SUCCESS: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_FILTERS_SUCCESS',
            FAILED: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_FILTERS_FAILED',
            SET: 'ADMIN_PANEL_IMAGES_CONTROL_PANEL_IMAGE_FILTERS_SET'
        }
    }
};
